DB_PATH        = "chatbot.db"
APP_NAME       = "AskPilot"
HOTKEY         = "ctrl+shift+z"
_FALLBACK_KEY  = "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"
_FALLBACK_MODEL = "llama-3.1-8b-instant"
